from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor


OUTPUT = Path(__file__).resolve().parents[1] / "Nomad_Wanderers_Implemented_Features.docx"


def bullets(document: Document, values: list[str]) -> None:
    for value in values:
        document.add_paragraph(value, style="List Bullet")


def main() -> None:
    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    document.styles["Normal"].font.name = "Aptos"
    document.styles["Normal"].font.size = Pt(10.5)
    for style_name in ("Title", "Heading 1", "Heading 2"):
        document.styles[style_name].font.name = "Aptos Display"
        document.styles[style_name].font.color.rgb = RGBColor(0, 92, 94)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("Nomad Wanderers\nImplemented Features")
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(0, 92, 94)
    document.add_paragraph("Current application demo build", style="Subtitle")

    document.add_heading("1. Public Website Experience", level=1)
    bullets(document, [
        "Premium responsive home page with a full-width auto-sliding tour carousel.",
        "Carousel displays tour image, title, description, Book this tour button, arrows and pagination dots.",
        "Responsive desktop and mobile navigation across all application pages.",
        "Trips menu with One-day trips, Weekly trips and Design your journey options.",
        "Modern travel-brand design with hero content, welcome panels, feature sections and social-media footer links.",
    ])

    document.add_heading("2. Tours and Trips", level=1)
    bullets(document, [
        "Tours page for browsing individual bookable experiences.",
        "Tours page search by tour name, description or category.",
        "Tours filters for Heritage, Food, Culture, Walking, Adventure, Shared and Private experiences.",
        "Trips pages for planning by duration and destination rather than duplicating the Tours page.",
        "One-day and Weekly trip pages with city selection for Mumbai and Delhi.",
        "Tours are controlled by City, Trip type, Tour format, Category, Duration, Price and Published status.",
        "Public pagination: Tours show 9 results per page and Trips show 6 results per page.",
    ])

    document.add_heading("3. Booking, Contact and Custom Journey", level=1)
    bullets(document, [
        "Book this tour flow captures traveller name, email, phone/WhatsApp number, preferred date and traveller count.",
        "General Contact form stores support and general travel messages.",
        "Design your journey form captures destinations, dates, duration, traveller count, budget and interests.",
        "Floating WhatsApp contact button for direct traveller communication.",
        "Booking flow is separate from Contact enquiries and proceeds directly to the demo checkout.",
    ])

    document.add_heading("4. Demo Payment Experience", level=1)
    bullets(document, [
        "Razorpay-style demo checkout screen for booking deposits.",
        "Simulated UPI, Credit card and Debit card payment-method selection.",
        "₹499 dummy booking-deposit workflow.",
        "Unique demo transaction reference generated by the backend.",
        "Success page with email-confirmation and WhatsApp-template previews.",
        "Demo payment records are shown in the admin dashboard.",
    ])
    document.add_paragraph("Demo limitation: no real money is collected and no live email or WhatsApp message is sent.")

    document.add_heading("5. Admin Dashboard", level=1)
    bullets(document, [
        "JWT-protected admin sign-in and logout flow.",
        "Tours management: create, edit, publish/unpublish, feature, delete, update image, price, city, duration and highlights.",
        "Clear distinction between Trip type (One-day / Weekly) and Tour format (Shared / Private).",
        "Contact enquiry management with status updates and admin follow-up notes.",
        "Custom journey management with status, itinerary notes and quotation fields.",
        "Demo payments tab with traveller, tour, amount, method and transaction reference.",
        "Search on every admin tab: Tours, Enquiries, Custom journeys and Demo payments.",
        "Six records per page in admin with Previous/Next pagination controls.",
    ])

    document.add_heading("6. Backend and Data Features", level=1)
    bullets(document, [
        "FastAPI backend with APIs exposed from main.py.",
        "Database schema and data-access functions separated into db_models.py.",
        "MySQL-ready data layer reading server-side connection settings from backend/db.env.",
        "Tables for Tours, Contact Enquiries, Custom Journeys, Demo Payments and revoked JWT tokens.",
        "Protected admin CRUD APIs for tours, enquiries and custom journeys.",
        "Server-side search and pagination for all admin collections.",
        "Server-side public pagination and filtering for Tours and Trips.",
    ])

    document.add_heading("7. Responsive Design and Content", level=1)
    bullets(document, [
        "Mobile navigation menu across public pages.",
        "Responsive card grids, forms, carousels, filters and admin controls.",
        "About page, contact page, footer, Facebook and Instagram icon links.",
        "Consistent Nomad Wanderers visual styling across public and admin areas.",
    ])

    document.add_heading("8. Next Production Integrations", level=1)
    bullets(document, [
        "Live Razorpay payment gateway with webhook verification.",
        "Email provider integration for real booking confirmations.",
        "WhatsApp Business API integration with approved message templates.",
        "Dedicated Customer, Guides, Promotions, Content and Reporting admin modules.",
        "Production user accounts, role-based access control, monitoring and database backup policies.",
    ])

    document.save(OUTPUT)
    print(OUTPUT)


if __name__ == "__main__":
    main()
